title: PassHemorrhage
description: Crack The Hell out of passwords
author: Chr0m0s0m3s
nav:
  - Social: 
    - type: 'Discord'
      Username: 'Chr0m0s0m3s#5254'
    - type: 'Steam'
      link: 'https://steamcommunity.com/id/chr0m0s0m3s'
theme: jekyll-theme-midnight
